### PR TITLE
Highlight git warnings

### LINKED ISSUE #5: [language-git] Warnings are not being highlighted
## User Info

- **Atom:** v1.14.4
- **OS:** macOS Sierra v10.12.3

---

Hey, Carlos! 👋 

First off, I'd like to say that this syntax theme is beautiful, and it's a treat to work with this theme. 👌 

## Issue

While writing a commit message, warnings (for example, when the subject line goes beyond 50 characters) are not being highlighted. 😔 

Material Dark: 

material-dark

One Dark: 

one-dark

## Solution

Adding the following in /styles/base.less 

```
.syntax--invalid {
    &.syntax--illegal {
        background-color: @red;
        color: @white;
    }

    &.syntax--deprecated {
        background-color: @orange;
        color: @white;
    }
}
```

instead of [lines 141-144](https://github.com/carloscuesta/material-syntax/blob/master/styles/base.less#L141) 

```
.syntax--invalid.syntax--illegal {
    background-color: @red;
    color: @white;
}
```

fixes the issue. 😎 

material-dark-fix

## Pull Request

Carlos, I can create a PR for this if you say so. 💪 

Cheers, 
Rishit

### PR DESCRIPTION
**Pull request by RishitKedia**
Fixes #5. 😎

### CODE REVIEW

**Review by carloscuesta — APPROVED** [review]
Do you know if`syntax--deprecated` selector is used in another languages files?

**Comment by carloscuesta** [comment]
Thanks @RishitKedia 🎉 !

**Comment by RishitKedia** [comment]
I think I did see it in some other languages' files too, but I'm not sure as I can't seem to find it now. 😛 

I made the decision to put this in /styles/base.less instead of /styles/languages/git.less because the 'One Dark' syntax theme [implements](https://github.com/atom/one-dark-syntax/blob/master/styles/syntax/_base.less#L254) it this way, so I thought those may be standardized selectors. 🙂 

Are you planning to release this? It would be nice if you could release this soon. 🙏 

Thanks, Carlos! 👍 🎉

**Comment by carloscuesta** [comment]
It's released now, it works I think 🎉

**Comment by RishitKedia** [comment]
Yes, it works now. Thanks! 👍 😃

**Pull request merged**
